server:
  port: 8010

spring:
  application:
    name: config-server
  profiles:
    # 默认是 git
    active: git
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://gitee.com/java-software/spring-cloud-config.git
  security:
    user:
      name: abc
      password: config123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    instance-id: config-8010
    prefer-ip-address: true
    # Eureka Client 给 Eureka Server 发送心跳的时间间隔，默认 30 单位是 s
    lease-renewal-interval-in-seconds: 1
    # Eureka Server 最后一次收到心跳的等待上线，超时剔除服务，默认 90 单位是 s
    lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh